version: '3'

services:
  app:
    build: ./
    image: sms
    expose:
      - 4040
    environment:
      NODE_ENV: production
      SERVER_PORT: 4040
      MONGO_HOST: mongodb://mongo/odmp
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
